default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: geospatial_development
  username: postgres
  password: password
  
test:
  <<: *default
  database: geospatial_test
  username: postgres
  password: password


production:
  <<: *default
  database: geospatial_production
  username: postgres
  password: password
